import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# Read the CSV generated by C++
df = pd.read_csv("data/potential_scan.csv")

phi = df['phi'].values
V = df['V'].values
lam = df['lambda_eff'].values
b_lam = df['beta_lambda'].values

# Calculate dV/dphi strictly from V to be consistent
# We can use np.gradient but since spacing is non-uniform, we use finite differences.
dV_dphi_fd = np.gradient(V, phi)

# Alternatively, the formula we exported approx:
dV_dphi_exact = df['dV_dphi'].values

# To determine properties robustly, let's use the finite difference which is exact for the data points.
dV_dphi = dV_dphi_fd

# Create the plots
fig, axs = plt.subplots(2, 2, figsize=(12, 10))

# 1. V(phi)
axs[0, 0].plot(phi, V, color='blue')
axs[0, 0].set_xscale('log')
# V(phi) becomes negative, so log scale for y might fail unless symlog or separate
# Let's just use linear for V, or symlog
axs[0, 0].set_yscale('symlog', linthresh=1e30) # V goes up to ~1e76, down to ~ -1e60 maybe
axs[0, 0].set_title(r'$V(\phi)$')
axs[0, 0].set_xlabel(r'$\phi$ (GeV)')
axs[0, 0].set_ylabel(r'$V(\phi)$')
axs[0, 0].grid(True, alpha=0.3)

# 2. dV/dphi
axs[0, 1].plot(phi, dV_dphi, color='red')
axs[0, 1].set_xscale('log')
axs[0, 1].set_yscale('symlog', linthresh=1e20)
axs[0, 1].set_title(r'$dV/d\phi$')
axs[0, 1].set_xlabel(r'$\phi$ (GeV)')
axs[0, 1].set_ylabel(r'$dV/d\phi$')
axs[0, 1].axhline(0, color='black', linestyle='--', alpha=0.5)
axs[0, 1].grid(True, alpha=0.3)

# 3. lambda_eff(phi)
axs[1, 0].plot(phi, lam, color='green')
axs[1, 0].set_xscale('log')
axs[1, 0].set_title(r'$\lambda_{eff}(\phi)$')
axs[1, 0].set_xlabel(r'$\phi$ (GeV)')
axs[1, 0].set_ylabel(r'$\lambda_{eff}$')
axs[1, 0].axhline(0, color='black', linestyle='--', alpha=0.5)
axs[1, 0].grid(True, alpha=0.3)

# 4. beta_lambda(phi)
axs[1, 1].plot(phi, b_lam, color='purple')
axs[1, 1].set_xscale('log')
axs[1, 1].set_title(r'$\beta_\lambda(\phi)$')
axs[1, 1].set_xlabel(r'$\phi$ (GeV)')
axs[1, 1].set_ylabel(r'$\beta_\lambda$')
axs[1, 1].axhline(0, color='black', linestyle='--', alpha=0.5)
axs[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("figures/potential_structure_plot.png", dpi=300)

# Determine Properties from V and dV/dphi
is_monotonic = np.all(np.diff(V) > 0) or np.all(np.diff(V) < 0)

# Sign changes in dV/dphi
sign_changes = np.where(np.diff(np.sign(dV_dphi)))[0]
does_dv_change_sign = len(sign_changes) > 0

# Does a barrier exist? A barrier implies V goes up then goes down, 
# meaning dV/dphi goes from positive to negative.
barrier_exists = False
second_min_exists = False

# Let's trace the potential structure
# We start at phi = 100 GeV. For physical potentials we expect it to start positive, go up (or down).
# Actually, the standard SM potential has a barrier if lambda goes negative.
# Let's see if there is any local maximum (dV/dphi changes from + to -)
for i in sign_changes:
    if dV_dphi[i] > 0 and dV_dphi[i+1] < 0:
        barrier_exists = True
    elif dV_dphi[i] < 0 and dV_dphi[i+1] > 0:
        second_min_exists = True

with open("POTENTIAL_STRUCTURE_REPORT.md", "w") as f:
    f.write("# Potential Structure Report\n\n")
    f.write("## Parameters\n")
    f.write(f"- $M_h$ = 5 GeV\n")
    f.write(f"- $M_t$ = 105 GeV\n\n")
    f.write("## Analysis based strictly on $V(\phi)$ and $dV/d\phi$\n\n")
    
    f.write("### 1. Is $V(\phi)$ strictly monotonic?\n")
    f.write(f"**{'Yes' if is_monotonic else 'No'}**. ")
    if not is_monotonic:
        f.write("The potential changes direction, as evidenced by $dV/d\phi$ changing sign.\n\n")
    else:
        f.write("The potential continually decreases or continually increases.\n\n")
        
    f.write("### 2. Does $dV/d\phi$ change sign?\n")
    f.write(f"**{'Yes' if does_dv_change_sign else 'No'}**. ")
    if does_dv_change_sign:
        f.write(f"Sign changes observed at $\\phi \\approx$ {[f'{phi[i]:.2e}' for i in sign_changes]} GeV.\n\n")
    else:
        f.write("The derivative maintains the same sign across the entire range.\n\n")
        
    f.write("### 3. Does a barrier exist?\n")
    f.write(f"**{'Yes' if barrier_exists else 'No'}**. ")
    if barrier_exists:
        f.write("There is a region where $dV/d\phi$ changes from positive to negative, indicating a local maximum (barrier) before the potential turns downward.\n\n")
    else:
        f.write("No local maximum was found in the specified range. The potential does not form a barrier.\n\n")
        
    f.write("### 4. Is there a second minimum?\n")
    f.write(f"**{'Yes' if second_min_exists else 'No'}**. ")
    if second_min_exists:
        f.write("There is a region where $dV/d\phi$ changes from negative to positive, indicating a local minimum at high field values.\n\n")
    else:
        f.write("No second minimum was found in the specified range. Once the potential turns downward, it does not turn back upward.\n\n")
        
    f.write("## Plots\n")
    f.write("![Potential Plots](figures/potential_structure_plot.png)\n")
    
print("Report generated: POTENTIAL_STRUCTURE_REPORT.md")
